# Generated by Django 3.2.7 on 2021-10-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Secretário'), (2, 'Paciente'), (3, 'Medico')]),
        ),
    ]
