# Generated by Django 3.2.7 on 2021-10-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info_cadastrada',
            field=models.BooleanField(null=True),
        ),
    ]
