# Generated by Django 3.2.7 on 2021-10-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_user_info_cadastrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info_cadastrada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
