# Generated by Django 3.2.7 on 2021-10-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SECRETARIO', 'Secretário'), ('PACIENTE', 'Paciente'), ('MEDICO', 'Medico')], max_length=15),
        ),
    ]
