# Generated by Django 3.2.7 on 2021-10-23 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qd', models.TextField()),
                ('hpma', models.TextField()),
                ('isda', models.TextField()),
                ('habitos', models.TextField()),
                ('antecedentes_pessoais', models.TextField()),
                ('antecedentes_familiares', models.TextField()),
                ('hipotese_cid', models.TextField()),
                ('conduta', models.TextField()),
                ('exames', models.TextField()),
                ('prescricoes', models.TextField()),
                ('evolucoes', models.TextField()),
                ('info_adicional', models.TextField()),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_medico_prontuario', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente_prontuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Informacao_Pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('profissao', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('documento', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('cor_raca', models.CharField(max_length=20)),
                ('naturalidade', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Aguardando Confirmação'), (1, 'Confirmado'), (2, 'Cancelado'), (3, 'Finalizado')])),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_medico_atendimento', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente_atendimento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
