# Generated by Django 3.2.7 on 2021-10-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
