# Generated by Django 3.2.7 on 2021-11-06 23:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prontuario',
            old_name='hpma',
            new_name='efg',
        ),
        migrations.RenameField(
            model_name='prontuario',
            old_name='isda',
            new_name='hda',
        ),
        migrations.RenameField(
            model_name='prontuario',
            old_name='prescricoes',
            new_name='receitas',
        ),
        migrations.AddField(
            model_name='informacao_pessoal',
            name='estado_civil',
            field=models.CharField(default='Solteiro', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacao_pessoal',
            name='plano_saude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informacao_pessoal',
            name='religiao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informacao_pessoal',
            name='reponsavel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='ref',
            field=models.CharField(default=datetime.date(2021, 11, 6), max_length=200),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='informacao_pessoal',
            name='id_paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('id_paciente', 'data_hora'), ('id_medico', 'data_hora')},
        ),
    ]
