# Generated by Django 3.2.7 on 2021-11-07 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211106_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='obs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='ref',
            field=models.CharField(default=datetime.date(2021, 11, 7), max_length=200),
        ),
    ]
