# Generated by Django 3.2.7 on 2021-10-31 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_prontuario_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('id_paciente', 'data_hora'), ('id_medico', 'data_hora')},
        ),
    ]
