# Generated by Django 3.2.7 on 2021-11-03 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211030_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prontuario',
            old_name='hpma',
            new_name='efg',
        ),
        migrations.RenameField(
            model_name='prontuario',
            old_name='isda',
            new_name='hda',
        ),
        migrations.RenameField(
            model_name='prontuario',
            old_name='prescricoes',
            new_name='receitas',
        ),
        migrations.AddField(
            model_name='informacao_pessoal',
            name='estado_civil',
            field=models.CharField(default='Solteiro', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacao_pessoal',
            name='plano_saude',
            field=models.CharField(default='Nenhum', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacao_pessoal',
            name='religiao',
            field=models.CharField(default='Nenhum', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacao_pessoal',
            name='reponsavel',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='ref',
            field=models.CharField(default=datetime.date(2021, 11, 3), max_length=200),
        ),
    ]
